php:
  build: .
  ports:
    - "80:81"
    - "443:443"
  volumes:
    - ./www:/var/www/html
  links:
    - db
db:
  image: mysql:5.7
  volumes:
    - /db/mysql
  environment:
    - MYSQL_ROOT_PASSWORD=phprs
    - MYSQL_DATABASE=phprs
